import os

#SAVED_RESULTS_ROOTDIR = os.getenv("SAVED_RESULTS_ROOTDIR")
SAVED_RESULTS_ROOTDIR = os.getcwd()
EARTHDATA_LOGIN = os.getenv("EARTHDATA_LOGIN")
EARTHDATA_PASSWORD = os.getenv("EARTHDATA_PASSWORD")
EDL_TOKEN = os.getenv("EDL_TOKEN")

EARTHDATA_MAX_NUM_REQUESTS_PER_SEC = int(os.getenv("EARTHDATA_MAX_NUM_REQUESTS_PER_SEC", 50))
