import os

#SAVED_RESULTS_ROOTDIR = os.getenv("SAVED_RESULTS_ROOTDIR")
SAVED_RESULTS_ROOTDIR = os.getcwd()
EARTHDATA_LOGIN = os.getenv("EARTHDATA_LOGIN")
EARTHDATA_PASSWORD = os.getenv("EARTHDATA_PASSWORD")
EDL_TOKEN = os.getenv("EDL_TOKEN")

EARTHDATA_MAX_NUM_REQUESTS_PER_SEC = int(os.getenv("EARTHDATA_MAX_NUM_REQUESTS_PER_SEC", 50))

B2_BUCKET_NAME = os.getenv("B2_BUCKET_NAME")
B2_ACCOUNT_ID = os.getenv("B2_ACCOUNT_ID")
B2_APPLICATION_KEY = os.getenv("B2_APPLICATION_KEY")
